import dotenv from 'dotenv';
import swaggerAutogen from 'swagger-autogen';

dotenv.config();

const port = process.env.PORT || 3000;

const doc = {
  info: {
    title: 'Survey API Overview',
    description: 'Survey API documentation generated by swagger-autogen',
  },
  host: `localhost:${port}`,
  schemes: ['http'],
};

const outputFile = './src/utils/swagger-output.json';
const routes = ['../index.js'];

swaggerAutogen()(outputFile, routes, doc).then(async () => {
  await import('../index.js');
});
